language: android
android:
  components:
    - tools 
    - tools 
    - platform-tools
    - build-tools-25.0.1
    - android-25

before_install:
 - chmod +x gradlew
 
script:
   - ./gradlew build connectedCheck
