language: android
android:
  components:
    - tools
    - platform-tools
    - tools # appears twice as per Travis docs
    - build-tools-25.0.1
    - android-25
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-25
    
env:
  matrix:
    - ANDROID_TARGET=android-25 ANDROID_ABI=armeabi-v7a
 
before_script:
  # Create and start emulator
  - android list targets
  - jdk_switcher use oraclejdk8
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-window &
  - adb wait-for-device
  - while [[ `adb shell pm path android` == 'Error'* ]]; do sleep 2; done
  - adb shell input keyevent 82 &

script: ./gradlew --info connectedAndroidTest

sudo: false
