language: android
android:
  components:
    - tools
    - platform-tools
    - tools # appears twice as per Travis docs
    - build-tools-25.0.1
    - android-25
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-17
 
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script: ./gradlew --info connectedAndroidTest

sudo: false
